version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: EmployeeDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  employee_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=this_is_a_super_secret_key_1234567890!@#$
      - Jwt__Issuer=EmployeeManagementAPI
    depends_on:
      - mysql
    ports:
      - "5000:80"

volumes:
  mysql_data:
