version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: EmployeeDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  employee_api:
    build:
      context: .    # Repository root is the build context.
      dockerfile: EmployeeManagement.API/Dockerfile
    container_name: employee_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=this_is_a_super_secret_key_1234567890!@#$
      - Jwt__Issuer=EmployeeManagementAPI
      - ConnectionStrings__EmployeeDatabase=Server=mysql;Port=3306;Database=EmployeeDB;Uid=root;Pwd=yourpassword;AllowPublicKeyRetrieval=True;SslMode=None;
    depends_on:
      - mysql
    ports:
      - "5000:80"

  employee_frontend:
    build:
      context: ./frontend/employee-management-frontend
      dockerfile: Dockerfile
    container_name: employee_frontend
    depends_on:
      - employee_api
    ports:
      - "4200:4200"

volumes:
  mysql_data:
